### ISSUE TITLE
Question about Referring QAs!

### ISSUE THREAD

**Issue by zhang-jr** [BAAI-DCAI/Visual-Instruction-Tuning#9]
Thank you for sharing. This question has also been raised in the context of [LRV](https://github.com/FuxiaoLiu/LRV-Instruction/issues/14).

In the process of utilizing a visual encoder, resizing images becomes necessary. Since there are no predefined pre-processing steps, a concern arises: how can we maintain consistency in the image coordinates within referring questions and answers, especially when dealing with resized images across different models?

**Comment by zhang-jr** [comment]
Is it handled in the same way as in [LLaVA](https://github.com/haotian-liu/LLaVA/issues/606)?

**Comment by BoyaWu10** [comment]
Hi @zhang-jr, thanks for raising this issue. The coordinates in referring QAs are based on the size of **original images**.

In LLaVA, images are padded to square before the visual encoder (by setting `--image_aspect_ratio pad`), the coordinates will also be changed due to the padding behavior. Here we provide a [script](https://github.com/BAAI-DCAI/Visual-Instruction-Tuning/blob/main/tools/expand_to_square.py) to help expand the bounding boxes to square as well. After running the script, you can feed the output data to LLaVA.

For other image resizing strategies, I think it will be required to preprocess the referring QAs accordingly, just as the one we do in above steps.

**Comment by BoyaWu10** [comment]
Here we provide a [script](https://github.com/BAAI-DCAI/Visual-Instruction-Tuning/blob/main/tools/expand_to_square.py) to help expand the bounding boxes to square. You can run the script to get QAs with expanded coordinates and feed the data to models like LLaVA, which pads images to square before the visual encoder.

**Comment by zhang-jr** [comment]
Thanks for your reply! It really helps a lot.
